#!/bin/bash

cd ~/op-worker
./erl_compile.sh $1
docker exec -it `hashdocker worker1.p1` find /root/bin/ -name $1.beam -exec cp /root/build/ebin/$1.beam {} ';'
docker exec -it `hashdocker worker1.p2` find /root/bin/ -name $1.beam -exec cp /root/build/ebin/$1.beam {} ';'
echo "code:soft_purge($1), code:load_file($1)."
