#!/bin/bash

cd ~/op-worker
./erl_compile.sh $1
docker exec -it `hashdocker worker1.p1` find /root/bin/ -name router.beam -exec cp /root/build/ebin/router.beam {} ';'
docker exec -it `hashdocker worker1.p2` find /root/bin/ -name router.beam -exec cp /root/build/ebin/router.beam {} ';'
